### ISSUE TITLE
Errror

### ISSUE THREAD

**Issue by JunkDaCoder** [dihydrogen-monoxide/Factions-pp#6]
Notice: Indirect modification of overloaded property pocketmine\utils\Config::$TEST has no effect in C:\Users\Conner\Documents\PocketMine-MP\plugins\Factions-pp-master\src\HittmanA\factionspp\MainClass.php on line 111
happens on /f leave, it removes the faction in the factions.json but not the players.json

**Comment by HittmanA** [comment]
There. Issue was because of a brainfart :/ .

**Comment by HittmanA** [comment]
Ughhhh didn't fix it...

**Comment by JunkDaCoder** [comment]
nor did i :(

**Comment by HittmanA** [comment]
Hmm
Come to gitter i guess

**Comment by HittmanA** [comment]
Fixed with commit 81.
